# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 14:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_type', models.CharField(default='Student', max_length=20)),
                ('avatar', models.FileField(null=True, upload_to='media/avatars/%Y/%m/%d/')),
                ('phone', models.CharField(default='None', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('generation_date', models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 32, 35, 995062))),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread', models.BooleanField(default=True)),
                ('content', models.TextField(default='None')),
                ('createTime', models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 32, 35, 994059))),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyTutors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default='0.00')),
                ('commission_rate', models.FloatField(default='0.05')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread', models.BooleanField(default=True)),
                ('category', models.CharField(default='booking', max_length=20)),
                ('content', models.TextField(default='This is a notification!')),
                ('createTime', models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 32, 35, 993056))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(default='3')),
                ('comment', models.TextField(default='')),
                ('anonymous', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 32, 35, 995062))),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_type', models.CharField(default='Student', max_length=20)),
                ('avatar', models.FileField(null=True, upload_to='media/avatars/%Y/%m/%d/')),
                ('phone', models.CharField(default='None', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookable', models.BooleanField(default=False)),
                ('cancellable', models.BooleanField(default=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('startTime', models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 32, 35, 993056))),
                ('endTime', models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 32, 35, 993056))),
                ('within_week', models.BooleanField(default=False)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(default='0.00')),
                ('content', models.TextField(default='This is a notification!')),
                ('createTime', models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 32, 35, 994059))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(null=True, upload_to='media/avatars/%Y/%m/%d/')),
                ('phone', models.CharField(default='None', max_length=10)),
                ('login_type', models.CharField(default='Tutor', max_length=20)),
                ('tutor_type', models.CharField(default='Contract', max_length=20)),
                ('change_type', models.BooleanField(default=False)),
                ('change_time', models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 32, 35, 991051))),
                ('change_rate', models.IntegerField(default=0)),
                ('course', models.ManyToManyField(to='tutoria.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=50)),
                ('hourly_rate', models.IntegerField(default=10)),
                ('average_review', models.IntegerField(default=-1)),
                ('introduction', models.TextField(default='This is an introduction')),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default='0.00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.TutorProfile'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tag',
            field=models.ManyToManyField(to='tutoria.Tag'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.Tutor'),
        ),
        migrations.AddField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.Student'),
        ),
        migrations.AddField(
            model_name='review',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.Tutor'),
        ),
    ]
