# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0002_auto_20171124_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='change_rate',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='change_time',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='change_type',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='generation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 34, 59, 809308)),
        ),
        migrations.AlterField(
            model_name='message',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 34, 59, 808306)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 34, 59, 807303)),
        ),
        migrations.AlterField(
            model_name='review',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 34, 59, 808306)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 34, 59, 807303)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 34, 59, 807303)),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 34, 59, 807303)),
        ),
    ]
