# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0003_auto_20171022_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='average_review',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
