# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0004_auto_20171124_2237'),
        ('tutoria', '0002_auto_20171124_2231'),
    ]

    operations = [
    ]
