# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0004_auto_20171022_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='average_review',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='hourly_rate',
            field=models.IntegerField(default=10),
        ),
    ]
