# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0004_auto_20171022_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Student'),
        ),
    ]
