# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0005_auto_20171022_1942'),
        ('tutoria', '0005_auto_20171023_2306'),
    ]

    operations = [
    ]
