# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0006_merge_20171023_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='booking', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.Student')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.Timeslot')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.Tutor')),
            ],
        ),
    ]
