# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0007_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.TextField(default='This is an avatar'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='tutor',
            name='avatar',
            field=models.TextField(default='This is an avatar'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='phone',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 10, 21, 29, 696176)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 10, 21, 29, 696176)),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='introduction',
            field=models.TextField(default='This is an introduction'),
        ),
    ]
