# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0008_auto_20171101_1021'),
        ('tutoria', '0007_auto_20171101_0047'),
    ]

    operations = [
    ]
