# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 03:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0009_merge_20171101_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='fee',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 11, 3, 44, 768758)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 11, 3, 44, 768758)),
        ),
    ]
