# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 05:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0017_auto_20171101_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 13, 32, 37, 141463)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 13, 32, 37, 141463)),
        ),
    ]
