# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 08:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutoria', '0020_auto_20171105_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_type', models.CharField(default='Student', max_length=20)),
                ('balance', models.IntegerField(default=0)),
                ('avatar', models.TextField(default='This is an avatar')),
                ('phone', models.CharField(default='None', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='tutor_type',
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor_type',
            field=models.CharField(default='Contract', max_length=20),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 16, 27, 26, 631994)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 16, 27, 26, 631994)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='login_type',
            field=models.CharField(default='Tutor', max_length=20),
        ),
    ]
