# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 09:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0021_auto_20171106_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='contact',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 10, 17, 38, 55, 203238)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 10, 17, 38, 55, 203238)),
        ),
    ]
