# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0023_auto_20171110_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='available_for_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='available_for_cancelling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='fee',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='balance',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='student',
            name='balance',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 10, 21, 7, 44, 64041)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 10, 21, 7, 44, 64041)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='balance',
            field=models.FloatField(default='0.00'),
        ),
    ]
