# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0026_auto_20171110_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default='0.00')),
            ],
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 10, 23, 44, 38, 460100)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 10, 23, 44, 38, 460100)),
        ),
    ]
