# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0027_auto_20171110_2344'),
        ('tutoria', '0025_auto_20171111_0300'),
    ]

    operations = [
    ]
