# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0029_auto_20171111_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 11, 16, 56, 40, 372769)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 11, 16, 56, 40, 372769)),
        ),
    ]
