# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 12:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0031_auto_20171111_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 11, 20, 1, 50, 929871)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 11, 20, 1, 50, 928871)),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='university',
            field=models.CharField(max_length=50),
        ),
    ]
