# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 14:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0032_auto_20171111_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 12, 22, 22, 46, 932209)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 12, 22, 22, 46, 932209)),
        ),
    ]
