# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0034_auto_20171113_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 14, 31, 57, 799022)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 14, 31, 57, 799022)),
        ),
    ]
