# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 11:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0035_auto_20171113_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytutor',
            name='commission_rate',
            field=models.FloatField(default='0.05'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 19, 22, 8, 380677)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 19, 22, 8, 380646)),
        ),
    ]
