# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 18:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutoria', '0036_auto_20171114_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='booking', max_length=20)),
                ('content', models.TextField(default='This is a notification!')),
                ('fee', models.FloatField(default='0.00')),
                ('createTime', models.DateTimeField(default=datetime.datetime(2017, 11, 17, 2, 58, 37, 899756))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(default='3')),
                ('comment', models.TextField(default='This is my review!')),
                ('anonymous', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.Student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.Tutor')),
            ],
        ),
        migrations.RemoveField(
            model_name='confirmation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='confirmation',
            name='timeslot',
        ),
        migrations.RemoveField(
            model_name='confirmation',
            name='tutor',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 2, 58, 37, 898755)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 2, 58, 37, 898755)),
        ),
        migrations.DeleteModel(
            name='Confirmation',
        ),
    ]
