# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0037_auto_20171119_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 23, 40, 52, 219163)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 23, 40, 52, 218162)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 23, 40, 52, 218162)),
        ),
    ]
