# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0037_auto_20171117_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 15, 38, 50, 752977)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 15, 38, 50, 751977)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 15, 38, 50, 751977)),
        ),
    ]
