# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 05:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0039_auto_20171121_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.CharField(default='HKU', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 13, 33, 13, 175264)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 13, 33, 13, 174764)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 13, 33, 13, 174764)),
        ),
    ]
