# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 08:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0041_auto_20171121_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 16, 32, 9, 869975)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 16, 32, 9, 868945)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 16, 32, 9, 867943)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 16, 32, 9, 867943)),
        ),
        migrations.AlterField(
            model_name='transcationrecord',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 16, 32, 9, 869447)),
        ),
    ]
