# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 08:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutoria', '0042_auto_20171121_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(default='0.00')),
                ('content', models.TextField(default='This is a notification!')),
                ('createTime', models.DateTimeField(default=datetime.datetime(2017, 11, 21, 16, 36, 2, 403364))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='transcationrecord',
            name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 16, 36, 2, 403853)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 16, 36, 2, 402349)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 16, 36, 2, 401848)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 16, 36, 2, 401848)),
        ),
        migrations.DeleteModel(
            name='TranscationRecord',
        ),
    ]
