# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 16:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0043_auto_20171121_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.CharField(default='The University of Hong Kong', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 0, 39, 23, 866490)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 0, 39, 23, 865490)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 0, 39, 23, 864489)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 0, 39, 23, 864489)),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 0, 39, 23, 866490)),
        ),
    ]
