# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 20:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0047_auto_20171122_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('generation_date', models.DateTimeField(default=datetime.datetime(2017, 11, 23, 4, 6, 48, 568528))),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 4, 6, 48, 567528)),
        ),
        migrations.AlterField(
            model_name='admin',
            name='avatar',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 4, 6, 48, 567528)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 4, 6, 48, 566527)),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 4, 6, 48, 565522)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 4, 6, 48, 565522)),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 4, 6, 48, 566527)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='avatar',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='average_review',
            field=models.IntegerField(default=-1),
        ),
    ]
