# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 07:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0049_auto_20171123_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='avatar',
            field=models.FileField(default='avatars/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='generation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 15, 58, 26, 199694)),
        ),
        migrations.AlterField(
            model_name='message',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 15, 58, 26, 197692)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 15, 58, 26, 196691)),
        ),
        migrations.AlterField(
            model_name='review',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 15, 58, 26, 198692)),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.FileField(default='avatars/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 15, 58, 26, 195690)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 15, 58, 26, 195690)),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 15, 58, 26, 197692)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='avatar',
            field=models.FileField(default='avatars/default.png', upload_to=''),
        ),
    ]
