# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0051_auto_20171123_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='avatar',
            field=models.FileField(null=True, upload_to='media/avatars/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='generation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 23, 50, 7, 636498)),
        ),
        migrations.AlterField(
            model_name='message',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 23, 50, 7, 635498)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 23, 50, 7, 634497)),
        ),
        migrations.AlterField(
            model_name='review',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 23, 50, 7, 635498)),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.FileField(null=True, upload_to='media/avatars/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 23, 50, 7, 633496)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 23, 50, 7, 633496)),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 23, 50, 7, 634497)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='avatar',
            field=models.FileField(null=True, upload_to='media/avatars/%Y/%m/%d/'),
        ),
    ]
