# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0058_auto_20171124_2000'),
        ('tutoria', '0057_auto_20171124_1709'),
    ]

    operations = [
    ]
